### ISSUE TITLE
View's autorun is being used in nonreactive context, leading to inconsistent behavior.

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-computed-field#15]
Because 0.5.0 version started using template's autorun, this creates a problem when you're creating computed fields that want to survive outside of that template. Usually, you create these fields inside a `Tracker.nonreactive` block (because you don't want them to be recreated when outside conditions change).

Concrete example:

Some template asks the model for some rich data object (`model.getData()`). The model wants to provide this object JIT and instantiates the class inside the `getData` call, but caches it in a private variable so it can return it immediately later without recreation. 

```
getData: ->
  @_object ?= Tracker.nonreactive => new RichClass
  …
  return @_object
```  
   
Now, this `RichClass` in its constructor wants to use computed fields. It does so with `dontStop` passed in so they keep running. However, when the template that asked for this data first is destroyed, the computed fields will be stopped, because under the hood they were using the asking template's autorun. This then prevents other dependant recalculations to work correctly. Only If the field is then asked directly to get its data, it will start running again and things will return to normal. This creates very inconsistent behavior that depends on where/when it was instantiated and from where/when it was called etc.

Since such computed fields are created in a nonreactive context, I think `Tracker.autorun` should be used regardless if there is a current Blaze view active or not. Or if `dontStop` was passed, but I see from surrounding issues that that was by design that `dontStop` doesn't prevent invalidation when the template is destroyed. Maybe there should be a cleaner way in general to instantiate a computed field that isn't tied to surrounding autoruns/templates.

**Comment by MatejJan** [comment]
And as soon as I tried to modify the existing code, I found this comment:

https://github.com/peerlibrary/meteor-computed-field/blob/c935bf56ba891ed8de36f23d6ddda9b03a3fc230/lib.js#L12

So I guess that answers my question. :)

**Comment by mitar** [comment]
He he. :-)

BTW, I have started moving data fetching outside of the template itself, to top-level. In a lazy manner. So the first time you ask for data it starts fetching it, and then it forever stays available, but updating it when necessary.

But why you do not chain `Tracker.nonreactive` and `Tracker.autorun` yourself? A bit verbose, but you can make yourself an utility function for this?

Do you ever want then to stop that autorun at all? If not when view is destroyed, then when?

**Comment by MatejJan** [comment]
Yup, that's exactly what I ended up doing(`nonreactive` `autorun` chain), but I like how the `ReactiveVar` is packaged in the `ComputedField`, so now I just created a variant called `LiveComputedField`.

```
class LiveComputedField
  constructor: (valueFunction, equalsFunction) ->
    lastValue = null

    autorunHandle = Tracker.nonreactive -> Tracker.autorun (computation) ->
      value = valueFunction()
      
      if lastValue
        lastValue.set value
        
      else
        lastValue = new ReactiveVar value, equalsFunction      
      
      ...
```

I do destroy the field, but manually by calling `stop` on it in the destructor of the object that instantiated it in the first place.
