### ISSUE TITLE
Possible to make this a ReactiveVar extension?

### ISSUE THREAD

**Issue by steph643** [peerlibrary/meteor-computed-field#4]
I have not tried the package yet, but it looks great and I wonder if it could be made a ReactiveVar extension:

``` javascript
var foobar = new ReactiveVar(function () {
  var sum = 0;
  collection.find({}, {fields: {value: 1}}).forEach(function (doc) {
    sum += doc.value;
  });
  return sum;
});

// Get the value
console.log(foobar.get());

// Set the value until next reactive computation
// (probably not so useful, but coherent with ReactiveVar semantic)
console.log(foobar.set(33));  
```

Couldn't this even be made part of the ReactiveVar package?

**Comment by mitar** [comment]
In fact this is part of my recent pair of packages where I gave up on `ReactiveVar` and created [ReactiveField](https://github.com/peerlibrary/meteor-reactive-field/). :-)

**Comment by mitar** [comment]
And while doing this package, @retronator already asked why I do not just make `ReactiveField` behave like this package, if you pass a function in. I like clear separation of things. I do not see any benefit in overloading. That something behaves so much  differently if you pass a function or if you pass a value in.

Also, `ReactiveField` has both a getter and setter, while this one has only a getter.

And I would like a theoretical use of being able to store functions into a `ReactiveField`.
